name: bike-sharing-demand-prediction
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - flask
  - gunicorn
  - pip
  - pip:
      - requests
      - joblib
      - xgboost
      - lightgbm